version: '3'

services:
  mariadb:
    container_name: mariadb
    build:
      context: .
      dockerfile: ./requirements/mariadb/Dockerfile
      args:
        - DB_NAME=${DB_NAME}
        - DB_USER=${DB_USER}
        - DB_PASS=${DB_PASS}
        - DB_ROOT=${DB_ROOT}
    volumes:
      - dbvolume:/var/lib/mysql/
    networks:
      - jgirard
  wordpress:
    container_name: wordpress
    build:
      context: .
      dockerfile: ./requirements/wordpress/Dockerfile
      args:
        - DB_NAME=${DB_NAME}
        - DB_USER=${DB_USER}
        - DB_PASS=${DB_PASS}
    volumes:
      - wpvolume:/var/www/
    networks:
      - jgirard
    depends_on:
      - mariadb
  nginx:
    container_name: nginx
    build:
      args:
        - DOMAIN_NAME=${DOMAIN_NAME}
        - SSL_KEY=${SSL_KEY}
        - SSL_CERT=${SSL_CERT}
      context: .
      dockerfile: ./requirements/nginx/Dockerfile
    volumes:
      - wpvolume:/var/www/
    networks:
      - jgirard
    depends_on:
      - wordpress
    ports:
      - 443:443
volumes:
  dbvolume:
    driver_opts:
      o: bind
      type: bind
      device: ${HOME}/data/mariadb
  wpvolume:
    driver_opts:
      o: bind
      type: bind
      device: ${HOME}/data/wordpress
networks:
  jgirard:
    name: jgirard
    driver: bridge